# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst
sudo: required
dist: trusty
services:
  - docker
language: generic
compiler:
  - gcc
notifications:
  email:
    recipients:
      - gm130s@gmail.com
env:
  global:
    - ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
    # install geckodriver for testing
    - ADDITIONAL_DEBS="firefox"
    - BEFORE_INIT="apt-get update && apt-get install -y curl && curl -L -o /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz && cd /tmp && tar xf geckodriver.tar.gz && chmod +x geckodriver && cp -f geckodriver /usr/local/bin && geckodriver --version"
  matrix:
    - CHECK_PYTHON3_COMPILE=true
    - ROS_DISTRO="indigo"
    - ROS_DISTRO="jade"
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="lunar"
    - ROS_DISTRO="melodic"
    - ROS_DISTRO="noetic"
matrix:
  fast_finish: true
  allow_failures:
    - env: ROS_DISTRO="jade"
    - env: ROS_DISTRO="lunar"
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - if [ "${CHECK_PYTHON3_COMPILE}" == "true" ]; then python3 -m compileall .; exit $?; fi
  - .ci_config/travis.sh
#  - source ./travis.sh  # Enable this when you have a package-local script 
